server:
  address: localhost
  port: 8081

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        ip: ${server.address}a
        port: ${server.port}
        server-addr: localhost:8848