server:
  address: localhost
  port: 8080

spring:
  ## redis 配置
  redis:
    host: 47.105.106.3
    port: 6379
    password: redis_123456
    timeout: 3000
  ## 数据库 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.106.3:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: demo
    password: demo
