server:
  address: localhost
  port: 8080

#security:
#  oauth2:
#    client:
#      client-id: test
#      client-secret: test_123456
#      registered-redirect-uri: https://chenyangjie.com.cn

spring:
  ## redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3000
  ## 数据库 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: demo
    password: demo
